version: '2'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:8080
    container_name: web
    volumes:
      - C:\Users\DKKs-Admin\Desktop\work oneAuthen\one-sign-web:/app